<?php
/**
 * This file is part of CustomerClassPrice4
 *
 * Copyright(c) Akira Kurozumi <info@a-zumi.net>
 *
 *  https://a-zumi.net
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\CustomerClassPrice4\Tests\Web\Admin\Product;


use Plugin\CustomerClassPrice4\Tests\Web\Admin\AbstractWebTestCase;

class ProductClassControllerTest extends AbstractWebTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test商品規格登録ページで一部の規格のチェックを外して保存して、再度登録した場合エラーにならないか()
    {
        self::markTestIncomplete();
    }
}
