<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) LOCKON CO.,LTD. All Rights Reserved.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\Noshi\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\Noshi\Entity\NoshiConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * Noshi Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoshiConfigRepository extends AbstractRepository
{
    /**
     * NoshiConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, NoshiConfig::class);
    }

    /**
     * @param int $id
     *
     * @return null|NoshiConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
