<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTnblfsj\EccubeDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTnblfsj/EccubeDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTnblfsj.legacy');

    return;
}

if (!\class_exists(EccubeDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTnblfsj\EccubeDevDebugProjectContainer::class, EccubeDevDebugProjectContainer::class, false);
}

return new \ContainerTnblfsj\EccubeDevDebugProjectContainer([
    'container.build_hash' => 'Tnblfsj',
    'container.build_id' => 'f98058c1',
    'container.build_time' => 1636033659,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTnblfsj');
